### ISSUE TITLE
CPU usage in v2

### ISSUE THREAD

**Issue by micsthepick** [micsthepick/JSVocalRedIso#3]
Either:

Optimize what's implemented: probably will not make it very far, and will likely never match old usage

and/or

release a simplified version which should take less cpu, but have more artifacts.

**Comment by micsthepick** [comment]
PRs welcome!

**Comment by FelipeZanabria** [comment]
What is a middle ground between version 1 and version 2 is to set the overlap factor variable to 4.

**Comment by micsthepick** [comment]
ok, all that needs to be done is simply changing this line as necessary: https://github.com/micsthepick/JSVocalRedIso/blob/f2426df71f88034f026bf9e52cbdb7c62825759e/vocalrediso.jsfx#L150
