### ISSUE TITLE
Glitchy audio when seeking

### ISSUE THREAD

**Issue by jamesWalker55** [micsthepick/JSVocalRedIso#7]
When doing a seek with the FX enabled, the audio glitches after a second then reverts back to normal. The glitch usually lasts for a split second but can be quite loud and distracting.

Demonstration: https://streamable.com/qyo7e8

I think this glitch was introduced with the [STFT release](https://github.com/micsthepick/JSVocalRedIso/releases/tag/v2.0.0), I don't remember encountering this issue when using the older versions.

**Comment by micsthepick** [comment]
Hi James, Is there any clicking when you bypass the main track FX and seek? I would also love to hear what that specific track sounds like with the older version, so I know what it should sound like.

**Comment by micsthepick** [comment]
I think I've found the issue, the STFT version removes the code that silences the initial 2 FFT frames that contain uninitialized memory (before the pdc delay is reached). I will reintroduce that code into the current version. In the meantime, you might want to try the version in #6 and see if that works well (it reintroduces the silencing code).

**Comment by micsthepick** [comment]
the actual issue seems to be with the template code (at least how I was using it) - the fft and output buffers were never cleared between each `@init` run. This should be fixed in that same Pull request (#6)

**Comment by jamesWalker55** [comment]
Sorry for the very late response, I never received any notifications about this issue and only just saw your comments.

I can confirm that both versions (original and MDCT) on that branch work correctly without any blips while seeking.

**Comment by micsthepick** [comment]
@jamesWalker55 I believe that this is also fixed for STFT in this latest version, so I will close the issue, but feel free to reply if you think it need to re-open or have any queries.
